// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DataList: typeof import('./src/components/DataList.vue')['default']
    DataPointList: typeof import('./src/components/DataPointList.vue')['default']
    HelpText: typeof import('./src/components/HelpText.vue')['default']
    MapComp: typeof import('./src/components/MapComp.vue')['default']
    MapData: typeof import('./src/components/MapData.vue')['default']
    MapDistance: typeof import('./src/components/MapDistance.vue')['default']
    MapMarker: typeof import('./src/components/MapMarker.vue')['default']
    MapNotice: typeof import('./src/components/MapNotice.vue')['default']
    MapOperation: typeof import('./src/components/MapOperation.vue')['default']
    MapRoute: typeof import('./src/components/MapRoute.vue')['default']
    PropForm: typeof import('./src/components/PropForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/Side.vue')['default']
  }
}
