// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Hello: typeof import('./src/components/Hello.vue')['default']
    Mapbox: typeof import('./src/components/Mapbox.vue')['default']
    MapComp: typeof import('./src/components/MapComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
