name: Xuyun Data Sync

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get source sha
        run: curl https://api.github.com/repos/lanseria/xuyun-map-data/branches/main --silent | grep "sha" | head -n1 > sha 

      - name: Update source sha
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update source sha"
          add: "sha"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
